/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    404: typeof import('./src/components/404.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    Container: typeof import('./src/components/Container.vue')['default']
    copy: typeof import('./src/compon./src/components/Swiper.vue]
    DefaultFooter: typeof import('./src/components/DefaultFooter.vue')['default']
    HelloWorld: typeof import('./src/components/Menu.vue')['default']
    ImageSwiper: typeof import('./src/components/ImageSwiper.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    MobileNavbar: typeof import('./src/components/MobileNavbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Swiper: typeof import('./src/components/Swiper.vue')['default']
  }
}
